### ISSUE TITLE
nova resize fails

### ISSUE THREAD

**Issue by javacruft** [lxc/nova-compute-lxd#33]
```
/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_client.py:187
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [req-fe87cb08-087a-4ae9-89f6-3e9efdba107c 867fcfc46d0444e5979a9457fdf006b1 9279a2a9d6ec42c09362e8c6c5043c8a - - -] [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de] Failed to migration container: 'criu'
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de] Traceback (most recent call last):
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_migrate.py", line 57, in migrate_disk_and_power_off
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     instance)
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_utils.py", line 212, in container_migrate
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     {'instance': instance_name, 'reason': ex}, instance=instance)
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 195, in __exit__
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     six.reraise(self.type_, self.value, self.tb)
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_utils.py", line 206, in container_migrate
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     host=instance.host)
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_client.py", line 48, in client
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     return func(lxd_client, **kwargs)
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_client.py", line 189, in container_migrate
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     return lxd.container_migrate(kwargs['instance'])
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/pylxd/api.py", line 210, in container_migrate
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     return self.container.container_migrate(container)
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/pylxd/container.py", line 119, in container_migrate
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     'criu': str(data['metadata']['criu']),
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de] KeyError: 'criu'
2015-09-23 17:11:40.037 27041 ERROR nclxd.nova.virt.lxd.container_migrate [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [req-fe87cb08-087a-4ae9-89f6-3e9efdba107c 867fcfc46d0444e5979a9457fdf006b1 9279a2a9d6ec42c09362e8c6c5043c8a - - -] [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de] Setting instance vm_state to ERROR
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de] Traceback (most recent call last):
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 6251, in _error_out_instance_on_exception
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     yield
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 3719, in resize_instance
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     timeout, retry_interval)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/driver.py", line 163, in migrate_disk_and_power_off
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     retry_interval)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_migrate.py", line 67, in migrate_disk_and_power_off
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     {'e': ex}, instance=instance)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 195, in __exit__
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     six.reraise(self.type_, self.value, self.tb)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_migrate.py", line 57, in migrate_disk_and_power_off
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     instance)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_utils.py", line 212, in container_migrate
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     {'instance': instance_name, 'reason': ex}, instance=instance)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 195, in __exit__
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     six.reraise(self.type_, self.value, self.tb)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_utils.py", line 206, in container_migrate
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     host=instance.host)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_client.py", line 48, in client
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     return func(lxd_client, **kwargs)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container_client.py", line 189, in container_migrate
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     return lxd.container_migrate(kwargs['instance'])
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/pylxd/api.py", line 210, in container_migrate
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     return self.container.container_migrate(container)
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]   File "/usr/lib/python2.7/dist-packages/pylxd/container.py", line 119, in container_migrate
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]     'criu': str(data['metadata']['criu']),
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de] KeyError: 'criu'
2015-09-23 17:11:40.051 27041 ERROR nova.compute.manager [instance: 1d6e3e6b-2877-47f8-bd8a-40a33dbca1de]
```

**Comment by javacruft** [comment]
This stack trace is no longer thrown; however the instance, once migrated, is not startable.  Nova appears to try to start the instance, but the container just drop back into a non-running state.

**Comment by zulcss** [comment]
This should be fixed now
